version: "3.9"

services:
  web:
    build: .
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rentcar
      POSTGRES_USER: user_rentcar
      POSTGRES_PASSWORD: rentcar6002
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A root worker -l info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A root beat -l info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  bot:
    build: .
    command: python bot/main.py
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
